<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Si-Ternak - Sitemap Sementara</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; background-color: #f4f7f6; color: #333; margin: 0; padding: 40px; }
        .container { max-width: 1000px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; text-align: center; border-bottom: 2px solid #eee; padding-bottom: 15px; }
        .section { margin-bottom: 30px; }
        .section-title { font-size: 1.2em; font-weight: bold; color: #34495e; margin-bottom: 15px; display: block; border-left: 4px solid #3498db; padding-left: 10px; }
        .button-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 15px; }
        .btn { display: block; padding: 12px 15px; background-color: #3498db; color: white; text-decoration: none; text-align: center; border-radius: 4px; transition: background 0.3s; font-size: 0.9em; }
        .btn:hover { background-color: #2980b9; }
        .btn-secondary { background-color: #95a5a6; }
        .btn-secondary:hover { background-color: #7f8c8d; }
        .footer { text-align: center; margin-top: 40px; font-size: 0.8em; color: #888; }
    </style>
</head>
<body>

<div class="container">
    <h1>Si-Ternak: Temporary Navigator</h1>
    
    <div class="section">
        <span class="section-title">Authentication & Admin</span>
        <div class="button-grid">
            <a href="<?= site_url('auth') ?>" class="btn">Login Page</a>
            <a href="<?= site_url('admin/dashboard') ?>" class="btn">Admin Dashboard</a>
            <a href="<?= site_url('admin/logout') ?>" class="btn btn-secondary">Logout</a>
        </div>
    </div>

    <div class="section">
        <span class="section-title">Main Features</span>
        <div class="button-grid">
            <a href="<?= site_url('dashboard') ?>" class="btn">User Dashboard</a>
            <a href="<?= site_url('inseminasi') ?>" class="btn">Inseminasi Index</a>
            <a href="<?= site_url('inseminasi/pkb') ?>" class="btn">PKB List</a>
            <a href="<?= site_url('inseminasi/kelahiran') ?>" class="btn">Kelahiran List</a>
        </div>
    </div>

    <div class="section">
        <span class="section-title">Master Data</span>
        <div class="button-grid">
            <a href="<?= site_url('master/petugas') ?>" class="btn">Data Petugas</a>
            <a href="<?= site_url('master/peternak') ?>" class="btn">Data Peternak</a>
            <a href="<?= site_url('master/hewan') ?>" class="btn">Data Hewan</a>
        </div>
    </div>

    <div class="section">
        <span class="section-title">Pakan & Produksi</span>
        <div class="button-grid">
            <a href="<?= site_url('pakan') ?>" class="btn">Jenis Pakan</a>
            <a href="<?= site_url('pakan/laporan_produksi') ?>" class="btn">Laporan Produksi</a>
            <a href="<?= site_url('pakan/laporan_bulanan') ?>" class="btn">Rekap Bulanan</a>
        </div>
    </div>

    <div class="section">
        <span class="section-title">Vaksinasi & Perkembangan</span>
        <div class="button-grid">
            <a href="<?= site_url('vaksinasi') ?>" class="btn">Vaksinasi Index</a>
            <a href="<?= site_url('vaksinasi/rekap') ?>" class="btn">Rekap Vaksin</a>
            <a href="<?= site_url('perkembangan/kelompok') ?>" class="btn">Kelompok Ternak</a>
            <a href="<?= site_url('perkembangan/laporan') ?>" class="btn">Laporan Perkembangan</a>
        </div>
    </div>

    <div class="section">
        <span class="section-title">Management</span>
        <div class="button-grid">
            <a href="<?= site_url('user') ?>" class="btn">User Management</a>
        </div>
    </div>

    <div class="footer">
        &copy; <?= date('Y') ?> Si-Ternak - Generated by Gemini CLI
    </div>
</div>

</body>
</html>
